fragment userFields on User {
    id
    name
    url
    gravatarHash
    createdAt

    scores {
      right
      wrong
      total
      bonus
      totalPercent
    }

    company {
      name
      url
    }
}
