query getBet($username: String!) {
  userByName(name: $username) {
    name
    url
    gravatarHash
    createdAt

    bonus {
      id
      dennyPregz

      killsNightKing {
        name
      }

      winsThrone {
        name
      }
    }

    company {
      name
      url
    }
  }

  victimsBetForUser(username: $username) {
    id
    status
    score

    victim {
      name
    }
  }
}
